priority_tokens:
  - "BTCUSDT"
  - "ETHUSDT"
  - "BNBUSDT"
  - "ADAUSDT"
  - "SOLUSDT"
  - "DOTUSDT"
  - "ATOMUSDT"
  - "NEARUSDT"
  - "AVAXUSDT"
  - "MATICUSDT"

only_priority_tokens: false
filter_trash_tokens: true
token_check_interval_seconds: 1

alert_on_priority_tokens:
  enabled: true
  timeout_minutes: 10
  chat_id: ""
  telegram_token: ""
